server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # O coração que faz o React-Router ou a History API funcionarem.
    # Redireciona todas as sub-páginas acessadas para a "index.html".
    location / {
        try_files $uri $uri/ /index.html;
    }
}
