version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: talentflow-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      # Se quiser, chame a senha original daqui
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jujuba}
      POSTGRES_DB: vagasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentflow-backend
    restart: always
    ports:
      - "8083:8083" # Permite que chamadas "localhost:8083/api" do frontend no navegador alcancem o painel
    environment:
      # O backend enxerga a "db" interna do container Docker automaticamente!
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vagasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-jujuba}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8083/api}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: talentflow-frontend
    restart: always
    ports:
      - "80:80" # Site na porta pura (localhost)
    depends_on:
      - backend

volumes:
  postgres_data:
